---
- name: Create directory to build packages
  file:
    path: '~/repos'
    state: directory

- name: Clone git repo
  git:
    repo: 'https://github.com/docker/compose.git'
    dest: '~/repos/docker_compose'
    version: '{{docker_compose_version}}'
  register: ret_clone_docker_compose

- block:
  - name: Build docker image
    command: 'docker build -t docker-compose:armhf -f Dockerfile.armhf .'
    args:
      chdir: '~/repos/docker_compose/'

  - name: Build docker-compose executable
    shell: 'docker run --rm --entrypoint="script/build/linux-entrypoint" -v $(pwd)/dist:/code/dist -v $(pwd)/.git:/code/.git "docker-compose:armhf"'
    args:
      chdir: '~/repos/docker_compose/'

  - name: Create symlink in executable path
    file:
      src: '~/repos/docker_compose/dist/docker-compose-Linux-armv7l'
      dest: '/usr/local/bin/docker-compose'
      owner: root
      group: root
      mode: 0755
      state: link
  when: ret_clone_docker_compose | changed
