---
- name: Create directory to build packages
  file:
    path: '~/repos'
    state: directory

- name: Clone git repo
  git:
    repo: 'https://github.com/docker/compose.git'
    dest: '~/repos/docker_compose'
    version: '{{docker_compose_version}}'
  register: ret_clone_docker_compose

- block:
  - name: Build docker image
    docker_image:
      name: 'docker-compose'
      tag: 'armhf'
      dockerfile: '~/repos/docker_compose/Dockerfile.armhf'
      force: yes

  - name: Build docker-compose executable
    docker_container:
      name: 'docker-compose'
      image: 'docker-compose:armhf'
      entrypoint: 'script/build/linux-entrypoint'
      volumes:
        - '~/repos/docker_compose/dist:/code/dist'
        - '~/repos/docker_compose/.git:/code/.git'
      auto_remove: yes

  - name: Create symlink in executable path
    file:
      src: '~/repos/docker_compose/dist/docker-compose-Linux-armv7l'
      dest: '/usr/local/bin/docker-compose'
      owner: root
      group: root
      mode: 0755
      state: link
  when: ret_clone_docker_compose | changed
