---
- include_tasks: '{{ansible_architecture}}.yml'

- name: Check version of docker-compose in use
  command: docker-compose version --short
  register: docker_compose_version_in_use
  changed_when: docker_compose_version_in_use.rc != 0

- name: Install command line completion for bash
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/{{docker_compose_version_in_use.stdout}}/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose-{{docker_compose_version_in_use.stdout}}
    mode: 0644
  register: docker_compose_bash_completion

- name: Create symbolic link to bash completion file
  file:
    state: link
    src: /etc/bash_completion.d/docker-compose-{{docker_compose_version_in_use.stdout}}
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644
    force: yes
  when: docker_compose_bash_completion | changed
