---
- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-x86_64
    dest: /usr/local/bin/docker-compose-{{docker_compose_version}}
    mode: 0755
    owner: root
    group: root
  register: install_docker_compose

- name: Create symbolic link to docker-compose binary
  file:
    state: link
    src: docker-compose-{{docker_compose_version}}
    dest: /usr/local/bin/docker-compose
    force: yes
    mode: 0755
    owner: root
    group: root
  when: install_docker_compose | changed

